server:
  port: 8888

spring:
  application:
    name: Gateway
  cloud:
    discovery:
      enabled: true
    consul:
      discovery:
        heartbeat:
          enabled: true
      host: 127.0.0.1
      port: 8500
      config:
        enabled=false:

eureka:
  instance:
    hostname: localhost
